services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: image-quality-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
    restart: unless-stopped
    networks:
      - image-quality-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: image-quality-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - image-quality-network

networks:
  image-quality-network:
    driver: bridge